name: Test Datawrapper
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install requests pandas
      - name: Esplora colonne PortWatch
        run: python portwatch_dw.py
        env:
          DW_TOKEN: ${{ secrets.DW_TOKEN }}
